arguments:
    csvtables:
        input_file_name: 'data/hour.csv'
        output_file_name: 'output/predictions.csv'
    data_columns:
        del_columns:
            instant: 'row_index'
            dteday: 'date'
        category_columns:
            season: 'season'
            yr: 'year'
            mnth : 'month'
            hr: 'hour'
            holiday: 'holiday_or_not'
            weekday: 'weekday'
            workingday: 'workingday_or_not'
            weathersit: 'weather_state'
        numeric_columns:
            temp: 'normalized_temp'
            atemp: 'normalized_feeling_temp'
            hum: 'humidity'
            windspeed: 'wind_speed'
            casual: 'count_of_casual_users'
            registered: 'count_of_registered_users'
        target_column:
            cnt: 'total_rental_bikes'
    grid_cv_params:
        max_depth:
            - 1
            - 2 
            - 3
            - 4
            - 5
        random_state:
            - 42
            - 53
            - 7
        n_estimators:
            - 10
            - 20
            - 30
            - 40
            - 50
            - 60
            - 70
            - 80
            - 90
            - 100
       